<h1><?php echo (isset($_SESSION['message']))?$_SESSION['message']:'';?></h1>
        <h2>General information about courses</h2>
        <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Course</th>
                        <th>Teacher</th>
                        <th>Delete course</th>
                        <th>Edit course</th>
                    </tr>
               </thead>
               <tbody>