        <h2><?=(isset($message))?$message:'' ?></h2>
        <h1>Relation_table</h1>
                <table>
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>Teacher</th>
                                <th>Student name</th>
                                <th>Email</th>
                            </tr>
                       </thead>
                       <tbody>